openapi: 3.0.0
info:
  title: REST API Canile Virtuale
  version: 1.0.0
tags:

servers:
  - url: http://localhost:3000/api/v1
components:
  schemas:
    Dog:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        breed:
          type: string
        age:
          type: integer
        status:
          type: string
          enum:
            - available
            - in-custody
            - adopted
    User:
      type: object
      properties:
        _id:
          type: string
        email:
          type: string
        dogs:
          type: array
          items:
            $ref: "#/components/schemas/Dog"
paths: {}
